server.servlet.context-path: /account

 

spring:
  application:
    name: paymentservice-service
  profiles:
    active: local
  h2:
    console:
      enabled: true
      path: /h2_console
      settings:
        web-allow-others: true
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    hibernate.ddl-auto: none
    jpa.show-sql: true
    hibernate.dialect: org.hibernate.dialect.H2Dialect

management:

  server:

    port: 8081

  security.enabled: false

  endpoint.prometheus.enabled: true

  endpoints:

    web:

      exposure:

        include: '*'

 

spring.jackson:

  default-property-inclusion: non_null

  deserialization:

    fail-on-unknown-properties: false

 

logging.level.root: DEBUG

 

createsigning:

  url: https://api.bdunet.dk:9443/signing/sydbank/v1

  apikey: JxBzZUXxw3osCeBaPZcurBYfZhIBbC2w